const ap1DailyPool = [
    {
        id: "AP1-BATCH1-001",
        unit: "Kinematics",
        topic: "Average Speed and Velocity",
        skill: "Mathematical Routines",
        difficulty: "Easy",
        image: "", 
        question: "A toy car travels a total distance of 20 meters along a straight track in a time of 4 seconds. What is the average speed of the toy car?",
        choices: ["$2~m/s$", "$4~m/s$", "$5~m/s$", "$80~m/s$"],
        correctIndex: 2,
        explanation: "Average speed is calculated by dividing the total distance traveled by the total time taken: $v = \\frac{d}{t} = \\frac{20\\text{ m}}{4\\text{ s}} = 5\\text{ m/s}$."
    },
    {
        id: "AP1-BATCH1-002",
        unit: "Kinematics",
        topic: "Multi-Object Motion",
        skill: "Mathematical Routines",
        difficulty: "Medium",
        image: "", 
        question: "Object 1 moves with a constant speed $v_1$ along a straight path. Object 2 starts from rest at the same initial position and time, accelerating at a constant rate $a$ in the same direction. How long does it take for Object 2 to catch up to Object 1?",
        choices: ["$t = \\frac{v_1}{a}$", "$t = \\frac{2v_1}{a}$", "$t = \\frac{v_1}{2a}$", "$t = \\sqrt{\\frac{2v_1}{a}}$"],
        correctIndex: 1,
        explanation: "Object 2 catches Object 1 when their positions are equal ($x_1 = x_2$). The position equation for Object 1 is $x_1 = v_1t$, and for Object 2 it is $x_2 = \\frac{1}{2}at^2$. Setting them equal: $v_1t = \\frac{1}{2}at^2$. Disregarding $t = 0$ and dividing by $t$ yields $v_1 = \\frac{1}{2}at$, which gives $t = \\frac{2v_1}{a}$."
    },
    {
        id: "AP1-BATCH1-003",
        unit: "Work, Energy, and Power",
        topic: "Springs and Simple Harmonic Motion",
        skill: "Mathematical Routines",
        difficulty: "Hard",
        image: "", 
        question: "A block of mass $m$ is attached to an ideal horizontal spring of spring constant $k$ and undergoes simple harmonic motion with amplitude $A$. What is the speed of the block when its displacement from equilibrium is equal to exactly half of its amplitude, $x = \\frac{1}{2}A$?",
        choices: ["$\\frac{\\sqrt{3}}{2} A \\sqrt{\\frac{k}{m}}$", "$\\frac{1}{2} A \\sqrt{\\frac{k}{m}}$", "$\\frac{3}{4} A \\sqrt{\\frac{k}{m}}$", "$A \\sqrt{\\frac{k}{m}}$"],
        correctIndex: 0,
        explanation: "By conservation of mechanical energy, the total energy at amplitude $A$ equals the sum of kinetic and potential energies at position $x$: $\\frac{1}{2}kA^2 = \\frac{1}{2}mv^2 + \\frac{1}{2}kx^2$. Substituting $x = \\frac{1}{2}A$ yields $\\frac{1}{2}kA^2 = \\frac{1}{2}mv^2 + \\frac{1}{8}kA^2 \\rightarrow \\frac{3}{8}kA^2 = \\frac{1}{2}mv^2$. Solving for $v$ gives $v = \\frac{\\sqrt{3}}{2} A \\sqrt{\\frac{k}{m}}$."
    },
    {
        id: "AP1-BATCH1-004",
        unit: "Kinematics",
        topic: "Constant Acceleration",
        skill: "Mathematical Routines",
        difficulty: "Easy",
        image: "", 
        question: "A runner starts from rest and accelerates at a constant rate of $2\\text{ m/s}^2$ along a straight path for 3 seconds. What is the runner's final speed?",
        choices: ["$1.5~m/s$", "$5~m/s$", "$6~m/s$", "$9~m/s$"],
        correctIndex: 2,
        explanation: "Using the kinematic equation $v_f = v_i + at$, where the runner starts from rest ($v_i = 0$), we get $v_f = 0 + (2\\text{ m/s}^2)(3\\text{ s}) = 6\\text{ m/s}$."
    },
    {
        id: "AP1-BATCH1-005",
        unit: "Kinematics",
        topic: "Two-Dimensional Motion",
        skill: "Concept Explanation",
        difficulty: "Medium",
        image: "", 
        question: "A standard projectile is launched into the air at an angle above a flat horizontal field. If air resistance is completely negligible, what is the orientation of the projectile's instantaneous velocity vector relative to its acceleration vector at the absolute highest point of its trajectory?",
        choices: ["The vectors point in the same direction.", "The vectors point in opposite directions.", "The vectors are perpendicular to each other.", "The velocity vector is zero, so no orientation exists."],
        correctIndex: 2,
        explanation: "At the absolute highest point of a projectile's trajectory, the vertical component of velocity is zero, leaving only the horizontal component ($v_x$). The acceleration vector points vertically downward due to gravity. Therefore, the velocity and acceleration vectors are completely perpendicular to each other."
    },
    {
        id: "AP1-BATCH1-006",
        unit: "Kinematics",
        topic: "Free Fall",
        skill: "Mathematical Routines",
        difficulty: "Easy",
        image: "", 
        question: "An object is dropped from rest from the edge of a tall cliff. If air resistance is negligible, how far does the object fall during the first 2 seconds of its flight? (Assume $g = 10\\text{ m/s}^2$)",
        choices: ["10 m", "20 m", "40 m", "45 m"],
        correctIndex: 1,
        explanation: "Using the kinematic formula for displacement from rest, $\\Delta y = \\frac{1}{2}gt^2$. Plugging in the given values yields $\\Delta y = \\frac{1}{2}(10\\text{ m/s}^2)(2\\text{ s})^2 = 20\\text{ m}$."
    },
    {
        id: "AP1-BATCH1-007",
        unit: "Work, Energy, and Power",
        topic: "Constant Power Delivery",
        skill: "Mathematical Routines",
        difficulty: "Hard",
        image: "", 
        question: "An experimental motorized cart of mass $m$ starts from rest on a frictionless horizontal track. The cart's engine delivers a constant mechanical power $P$ directly into propelling the vehicle forward. What is the instantaneous speed of the cart as a function of time $t$?",
        choices: ["$\\sqrt{\\frac{2Pt}{m}}$", "$\\frac{Pt}{m}$", "$\\sqrt{\\frac{Pt}{2m}}$", "$\\frac{2Pt}{m}$"],
        correctIndex: 0,
        explanation: "Power is work done per unit time, so for a constant power engine, the work done in time $t$ is $W = Pt$. By the work-energy theorem, this work goes entirely into increasing the kinetic energy of the cart starting from rest: $W = \\Delta K \\rightarrow Pt = \\frac{1}{2}mv^2$. Solving for speed gives $v = \\sqrt{\\frac{2Pt}{m}}$."
    },
    {
        id: "AP1-BATCH1-008",
        unit: "Kinematics",
        topic: "Horizontal Projectiles",
        skill: "Mathematical Routines",
        difficulty: "Easy",
        image: "", 
        question: "A ball is kicked horizontally off the edge of a flat roof with an initial horizontal speed of $8\\text{ m/s}$. If it takes 3 seconds to strike the ground, what is the horizontal distance it travels before landing?",
        choices: ["24 m", "30 m", "45 m", "72 m"],
        correctIndex: 0,
        explanation: "In projectile motion, horizontal velocity remains constant because there is no horizontal acceleration ($a_x = 0$). The horizontal distance is $\\Delta x = v_x \\cdot t = (8\\text{ m/s})(3\\text{ s}) = 24\\text{ m}$."
    },
    {
        id: "AP1-BATCH1-009",
        unit: "Kinematics",
        topic: "Interpreting Graphs",
        skill: "Concept Explanation",
        difficulty: "Easy",
        image: "", 
        question: "A position-time graph for an object moving along a straight line shows a straight line sloping upward. What does this indicate about the object's motion?",
        choices: ["The object is stationary.", "The object is moving at a constant, non-zero velocity.", "The object is accelerating at a constant rate.", "The object is slowing down to a stop."],
        correctIndex: 1,
        explanation: "The slope of a position-time graph represents the velocity of the object. A straight, diagonal line has a constant slope, meaning the velocity remains steady and unchanging over time."
    },
    {
        id: "AP1-BATCH1-010",
        unit: "Kinematics",
        topic: "Vertical Motion Profiles",
        skill: "Mathematical Routines",
        difficulty: "Medium",
        image: "", 
        question: "A stone is thrown vertically upward with an initial launch speed of $v_0$. Neglecting air resistance, what is the instantaneous speed of the stone when it reaches exactly half of its maximum peak vertical height?",
        choices: ["$\\frac{1}{2}v_0$", "$\\frac{1}{\\sqrt{2}}v_0$", "$\\sqrt{2}v_0$", "$\\frac{\\sqrt{3}}{2}v_0$"],
        correctIndex: 1,
        explanation: "Using the kinematic equation $v_f^2 = v_0^2 + 2a\\Delta y$, at peak height ($v_f = 0$ and $a = -g$), the maximum height is $y_{\\text{max}} = \\frac{v_0^2}{2g}$. At half maximum height ($\\Delta y = \\frac{y_{\\text{max}}}{2} = \\frac{v_0^2}{4g}$), substituting back gives $v^2 = v_0^2 - 2g(\\frac{v_0^2}{4g}) = \\frac{1}{2}v_0^2$. Taking the square root gives $v = \\frac{v_0}{\\sqrt{2}}$."
    },
    {
        id: "AP1-BATCH1-011",
        unit: "Force and Translational Dynamics",
        topic: "Newton's Second Law",
        skill: "Mathematical Routines",
        difficulty: "Easy",
        image: "", 
        question: "A constant horizontal net force of 15 N is applied to a 5-kg block on a frictionless surface. What is the magnitude of the block's acceleration?",
        choices: ["$0.33\\text{ m/s}^2$", "$3.0\\text{ m/s}^2$", "$5.0\\text{ m/s}^2$", "$75.0\\text{ m/s}^2$"],
        correctIndex: 1,
        explanation: "According to Newton's second law ($F_{\\text{net}} = ma$), the acceleration is equal to the net force divided by the mass: $a = \\frac{F}{m} = \\frac{15\\text{ N}}{5\\text{ kg}} = 3\\text{ m/s}^2$."
    },
    {
        id: "AP1-BATCH1-012",
        unit: "Kinematics",
        topic: "Graph Analysis and Motion Phases",
        skill: "Mathematical Routines",
        difficulty: "Medium",
        image: "", 
        question: "An object moves along a straight line. It starts from rest, moves forward with a constant speed $v_{\\text{forward}}$ for 3 seconds, then instantly switches direction and moves backward with a constant speed $v_{\\text{backward}}$ for 2 seconds. If the object finishes exactly back at its starting position, what is the ratio of $v_{\\text{backward}}$ to $v_{\\text{forward}}$?",
        choices: ["2:3", "1:1", "3:2", "9:4"],
        correctIndex: 2,
        explanation: "For the total displacement to be zero over the 5-second interval, the forward displacement must equal the magnitude of the backward displacement ($x_{\\text{forward}} = x_{\\text{backward}}$). Because $\\Delta x = v \\cdot \\Delta t$, we set up the equation: $v_{\\text{forward}} \\cdot (3\\text{ s}) = v_{\\text{backward}} \\cdot (2\\text{ s})$. Solving for the ratio gives $\\frac{v_{\\text{backward}}}{v_{\\text{forward}}} = \\frac{3}{2}$."
    },
    {
        id: "AP1-BATCH1-013",
        unit: "Work, Energy, and Power",
        topic: "Non-Conservative Work and Inclines",
        skill: "Mathematical Routines",
        difficulty: "Hard",
        image: "", 
        question: "A block is released from rest against a compressed ideal horizontal spring at the base of an inclined plane tilted at an angle $\\theta$ above the horizontal. The spring is initially compressed by a distance $x$ and has a spring constant $k$. The block is launched up the incline, sliding a total distance $d$ along the rough surface before coming to a stop. If the coefficient of kinetic friction between the block and the incline is $\\mu_k$, which equation correctly expresses the conservation of energy for this process?",
        choices: ["$\\frac{1}{2} k x^2 = mg d \\sin\\theta + \\mu_k mg d \\cos\\theta$", "$\\frac{1}{2} k x^2 = mg d \\cos\\theta + \\mu_k mg d \\sin\\theta$", "$\\frac{1}{2} k x^2 + \\mu_k mg d \\cos\\theta = mg d \\sin\\theta$", "$\\frac{1}{2} k x^2 = mg d \\sin\\theta - \\mu_k mg d \\cos\\theta$"],
        correctIndex: 0,
        explanation: "The initial energy stored in the system is elastic potential energy, $U_s = \\frac{1}{2} k x^2$. As the block moves up the track, this energy converts into gravitational potential energy ($mg d \\sin\\theta$) and is dissipated as thermal energy due to non-conservative friction work ($W_f = f_k d = \\mu_k F_N d = \\mu_k mg d \\cos\\theta$). Thus, $\\frac{1}{2} k x^2 = mg d \\sin\\theta + \\mu_k mg d \\cos\\theta$."
    },
    {
        id: "AP1-BATCH1-014",
        unit: "Force and Translational Dynamics",
        topic: "Mass vs. Weight",
        skill: "Concept Explanation",
        difficulty: "Easy",
        image: "", 
        question: "An astronaut travels from Earth to the Moon, where the local gravitational field is weaker. How do the astronaut's mass and weight on the Moon compare to their values on Earth?",
        choices: ["Mass decreases; weight decreases.", "Mass remains the same; weight remains the same.", "Mass decreases; weight remains the same.", "Mass remains the same; weight decreases."],
        correctIndex: 3,
        explanation: "Mass is an intrinsic property representing the amount of matter in an object and does not change with location. Weight is the gravitational force acting on that mass ($W = mg$). Because the Moon's gravity $g$ is weaker than Earth's, the astronaut's weight decreases while their mass stays identical."
    },
    {
        id: "AP1-BATCH1-015",
        unit: "Kinematics",
        topic: "Stopping Distance Scaling",
        skill: "Mathematical Routines",
        difficulty: "Medium",
        image: "", 
        question: "A car traveling along a straight horizontal road at an initial speed $v$ locks its brakes and skids a distance $d$ before sliding to a complete stop under a constant braking deceleration. If the car were instead traveling at an initial speed of $3v$ and undergoes the exact same constant deceleration, what total skidding distance would it require to stop?",
        choices: ["$3d$", "$\\sqrt{3}d$", "$6d$", "$9d$"],
        correctIndex: 3,
        explanation: "Using the kinematic equation $v_f^2 = v_i^2 + 2ax$ with $v_f = 0$, we find that $0 = v_i^2 - 2|a|d \\rightarrow d = \\frac{v_i^2}{2|a|}$. This shows that stopping distance is directly proportional to the square of the initial speed ($d \\propto v_i^2$). Tripling the speed ($3v$) results in a stopping distance that increases by $3^2 = 9$, making it $9d$."
    },
    {
        id: "AP1-BATCH1-016",
        unit: "Force and Translational Dynamics",
        topic: "Normal Force and Friction",
        skill: "Mathematical Routines",
        difficulty: "Easy",
        image: "", 
        question: "A 2-kg book rests completely stationary on a flat horizontal table. What is the magnitude of the upward normal force exerted by the table surface on the book? (Assume $g = 10\\text{ m/s}^2$)",
        choices: ["0 N", "2 N", "10 N", "20 N"],
        correctIndex: 3,
        explanation: "Because the book is at rest, its acceleration is zero, meaning the net vertical force must be zero ($F_{\\text{net}} = 0$). The upward normal force must perfectly balance the downward force of gravity: $F_N = mg = (2\\text{ kg})(10\\text{ m/s}^2) = 20\\text{ N}$."
    },
    {
        id: "AP1-BATCH1-017",
        unit: "Work, Energy, and Power",
        topic: "Work Done by a Constant Force",
        skill: "Mathematical Routines",
        difficulty: "Easy",
        image: "", 
        question: "A gardener pushes a lawnmower along a flat patch of grass by applying a steady horizontal force of 10 N. If the gardener pushes the lawnmower a forward straight-line distance of 5 meters, how much total work is done by the gardener on the lawnmower?",
        choices: ["2 J", "15 J", "50 J", "250 J"],
        correctIndex: 2,
        explanation: "Work is calculated using the formula $W = Fd\\cos\\theta$. Because the force is applied in the same direction as the displacement ($\\theta = 0^\\circ$), the work done is simply $W = F \\cdot d = 10\\text{ N} \\cdot 5\\text{m} = 50\\text{ J}$."
    },
    {
        id: "AP1-BATCH1-018",
        unit: "Kinematics",
        topic: "Simultaneous Projectile Launch",
        skill: "Concept Explanation",
        difficulty: "Medium",
        image: "", 
        question: "Two toy darts, Dart A and Dart B, are fired horizontally from the exact same vertical height above a flat, level floor. Dart A has a mass of $m$ and is fired with an initial horizontal velocity $v_0$. Dart B has a mass of $2m$ and is fired with an initial horizontal velocity $2v_0$. If air resistance is completely negligible, which dart strikes the floor first?",
        choices: ["Dart A lands first.", "Dart B lands first.", "Both darts land at the exact same time.", "The landing time depends on the initial speeds."],
        correctIndex: 2,
        explanation: "Horizontal and vertical motions are completely independent. Since both darts are launched horizontally from the exact same height, their initial vertical velocities are zero, and they experience identical vertical acceleration ($g$). Consequently, they take the exact same amount of time to strike the floor, regardless of mass or horizontal speed."
    },
    {
        id: "AP1-BATCH1-019",
        unit: "Work, Energy, and Power",
        topic: "Vertical Trajectories and Energy Systems",
        skill: "Mathematical Routines",
        difficulty: "Hard",
        image: "", 
        question: "A small block of mass $m$ is held at a height $h$ above the uncompressed top of a vertical ideal spring fixed to the floor, which has a spring constant $k$. The block is dropped from rest, hits the spring, and compresses it by a maximum downward vertical distance $x$ before momentarily coming to a stop. Which equation properly describes the relationship between these parameters?",
        choices: ["$\\frac{1}{2}kx^2 - mgx - mgh = 0$", "$\\frac{1}{2}kx^2 - mgx + mgh = 0$", "$\\frac{1}{2}kx^2 + mgx - mgh = 0$", "$\\frac{1}{2}kx^2 + mgx + mgh = 0$"],
        correctIndex: 0,
        explanation: "Choosing the point of maximum spring compression as the reference origin ($U_g = 0$), the initial mechanical energy is entirely gravitational potential: $E_i = mg(h + x)$. At maximum compression, the block stops momentarily, so the final energy is entirely elastic potential: $E_f = \\frac{1}{2}kx^2$. Equating them gives $\\frac{1}{2}kx^2 = mg(h + x)$, which rearranges to $\\frac{1}{2}kx^2 - mgx - mgh = 0$."
    },
    {
        id: "AP1-BATCH1-020",
        unit: "Force and Translational Dynamics",
        topic: "Apparent Weight and Elevators",
        skill: "Mathematical Routines",
        difficulty: "Medium",
        image: "", 
        question: "A passenger of mass 60 kg stands on a platform scale inside an elevator that is moving downward while slowing down to a stop with a constant deceleration of magnitude $2\\text{ m/s}^2$. What is the reading on the scale during this interval? (Assume $g = 10\\text{ m/s}^2$)",
        choices: ["360 N", "480 N", "600 N", "720 N"],
        correctIndex: 3,
        explanation: "The elevator is moving downward but slowing down, meaning its acceleration vector points upward ($a = +2\\text{ m/s}^2$). Setting up Newton's second law with upward as positive: $F_N - mg = ma \\rightarrow F_N = m(g + a)$. Substituting the values gives $F_N = 60\\text{ kg}(10\\text{ m/s}^2 + 2\\text{ m/s}^2) = 60 \\cdot 12 = 720\\text{ N}$."
    },
    {
        id: "AP1-BATCH1-021",
        unit: "Planetary Gravitation",
        topic: "Interior Shell Theorem",
        skill: "Mathematical Routines",
        difficulty: "Medium",
        image: "", 
        question: "A hypothetical solid, uniform spherical planet has a total mass $M$ and a radius $R$. A small research probe of mass $m$ is lowered down a narrow shaft to a distance of exactly $\\frac{1}{2}R$ from the absolute center of the planet. What is the magnitude of the net gravitational force exerted by the planet on the probe at this deep interior location?",
        choices: ["Zero", "$\\frac{1}{8}\\frac{GMm}{R^2}$", "$\\frac{1}{4}\\frac{GMm}{R^2}$", "$\\frac{1}{2}\\frac{GMm}{R^2}$"],
        correctIndex: 3,
        explanation: "According to the shell theorem, when an object is inside a uniform solid planet at a distance $r$ from the center, only the mass contained within a sphere of radius $r$ exerts a net gravitational force. The interior mass scales with volume: $M_{\\text{inside}} = M(\\frac{r}{R})^3$. For $r = \\frac{1}{2}R$, $M_{\\text{inside}} = \\frac{1}{8}M$. The force is then $F = \\frac{G M_{\\text{inside}} m}{r^2} = \\frac{G (M/8) m}{(R/2)^2} = \\frac{1/8}{1/4}\\frac{GMm}{R^2} = \\frac{1}{2}\\frac{GMm}{R^2}$."
    },
    {
        id: "AP1-BATCH1-022",
        unit: "Fluids",
        topic: "Solid Body Geometric Volumes",
        skill: "Mathematical Routines",
        difficulty: "Medium",
        image: "", 
        question: "A solid aluminum block has a mass of exactly $2.7\\text{ kg}$. If the density of aluminum is known to be constant at $2700\\text{ kg/m}^3$, what is the geometric volume occupied by this specific block?",
        choices: ["$0.001\\text{ m}^3$", "$0.01\\text{ m}^3$", "$0.1\\text{ m}^3$", "$1.0\\text{ m}^3$"],
        correctIndex: 0,
        explanation: "Density is defined as $\\rho = \\frac{m}{V}$. Rearranging the formula to solve for volume gives $V = \\frac{m}{\\rho}$. Substituting the given values: $V = \\frac{2.7\\text{ kg}}{2700\\text{ kg/m}^3} = 0.001\\text{ m}^3$."
    },
    {
        id: "AP1-BATCH1-023",
        unit: "Fluids",
        topic: "Buoyant Force",
        skill: "Concept Explanation",
        difficulty: "Easy",
        image: "", 
        question: "A wooden block with a total weight of 12 N floats completely statically at rest at the surface of a pool of water. What is the magnitude of the upward buoyant force exerted by the water on the wooden block?",
        choices: ["Less than 12 N", "Exactly 12 N", "Greater than 12 N", "0 N"],
        correctIndex: 1,
        explanation: "For any object floating statically at the surface, the net vertical force is zero ($F_{\\text{net}} = 0$). Therefore, the upward buoyant force must exactly balance the downward force of gravity (the object's weight), making it exactly 12 N."
    },
    {
        id: "AP1-BATCH1-024",
        unit: "Work, Energy, and Power",
        topic: "Rigid Rod Vertical Rotation Constraints",
        skill: "Mathematical Routines",
        difficulty: "Hard",
        image: "", 
        question: "A small object of mass $m$ is fixed to the end of a rigid, lightweight structural rod of length $L$. The other end of the rod is attached to a frictionless pivot. The object hangs vertically at rest at its lowest equilibrium position. What minimum initial horizontal speed must be given to the object at the bottom so that it can successfully swing in a full, complete vertical circle around the pivot point?",
        choices: ["$\\sqrt{5gL}$", "$\\sqrt{4gL}$", "$\\sqrt{2gL}$", "$\\sqrt{gL}$"],
        correctIndex: 1,
        explanation: "Unlike a flexible string, a rigid rod can support compressive forces, meaning the object does not lose contact or collapse if its speed drops to zero at the top ($v_{\\text{top}} = 0$). By conservation of mechanical energy between the bottom and the top: $\\frac{1}{2}mv_{\\text{bottom}}^2 = mg(2L) + 0 \\rightarrow v_{\\text{bottom}} = \\sqrt{4gL}$."
    },
    {
        id: "AP1-BATCH1-025",
        unit: "Work, Energy, and Power",
        topic: "Translational Kinetic Energy",
        skill: "Mathematical Routines",
        difficulty: "Easy",
        image: "", 
        question: "A 2-kg toy airplane glides through the air with a constant translational speed of $4\\text{ m/s}$. What is the kinetic energy of the toy airplane?",
        choices: ["4 J", "8 J", "16 J", "32 J"],
        correctIndex: 2,
        explanation: "Kinetic energy is given by the formula $K = \\frac{1}{2}mv^2$. Plugging in the values: $K = \\frac{1}{2}(2\\text{ kg})(4\\text{ m/s})^2 = 1 \\cdot 16 = 16\\text{ J}$."
    }
];
